name: Publish

on:
  push:
    tags:
      - '*'

jobs:
  build:
    name: Publish binaries
    runs-on: ubuntu-latest

    steps:
    - name: Free space
      run: |
        sudo du -d 1 -h / || echo ""
        sudo rm -rf /usr/share/dotnet
        sudo rm -rf /opt/ghc
        sudo rm -rf "/usr/local/share/boost"
        sudo rm -rf "$AGENT_TOOLSDIRECTORY"
        sudo du -d 1 -h / || echo ""
    - name: Clone
      uses: actions/checkout@v3
      with:
        submodules: recursive
    - name: Build
      run: bash ./docker_build_riscv.sh
    - name: Create release
      uses: ncipollo/release-action@v1
      with:
        artifacts: "release/*"
        token: ${{ secrets.GITHUB_TOKEN }}

